org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.82

mod_id=dnfenhance
mod_name=DNF Enhance
mod_license=All Rights Reserved
mod_version=3.3.0-26.2-NeoForge
mod_group_id=com.xulai.dnfenhance
